steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/RAGify", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/RAGify"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "RAGify",
        "--image",
        "gcr.io/$PROJECT_ID/RAGify",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "GROQ_API_KEY=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",
      ]

images:
  - "gcr.io/$PROJECT_ID/RAGify"
